### ISSUE TITLE
The flags in diplomacy screen are darker.

### ISSUE THREAD

**Issue by PanosPetras** [PanosPetras/The_Great_War#21]
For some reason the flags in the diplomacy screen are now darker. I noticed this in the current commit. I have no idea what the cause is. I think yesterday it was still working fine.
![image](https://user-images.githubusercontent.com/49565684/232729605-43368868-f6b3-41a4-a7fb-8ace064d449b.png)

**Comment by TedLyngmo** [comment]
Aha, I set the activeTexture to inactive which wasn't done before. I'm not at my computer now, but it should only be removing one line.

**Comment by TedLyngmo** [comment]
Fixed by [1606ebd](https://github.com/PanosPetras/The_Great_War/commit/1606ebd38e134b13e6cc9623edadd98e82d91ff0)
