### ISSUE TITLE
Replace CountryBalances.txt with CountryStockpiles.txt

### ISSUE THREAD

**Issue by TedLyngmo** [PanosPetras/The_Great_War#24]
It seems you've prepared to load the whole stockpiles from file. Is that idea old or should I just create `CountryStockpiles.txt` with the balances from `CountryBalances.txt` ? If so, loading on start will become very clean.

**Comment by PanosPetras** [comment]
That is the whole idea. It was just to much effort to sit down and write the stockpiles file and I left it for later.

**Comment by TedLyngmo** [comment]
Ok, then if this patch doesn't mess up the zooming, that work is now done :)
